language: node_js
node_js:
  - "node"
branches:
  only:
    - wildo
    - loggin
    - dev
    - master
jobs:
  include:
    - stage: style
      script: npm run lint
    - stage: test
      script: npm run test